const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const C=APP_CONTENT.categories, D=APP_CONTENT.details, K=APP_CONTENT.knowledge;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function renderCategories(filter=''){const f=filter.toLowerCase();const list=C.filter(c=>(c.title+' '+c.short+' '+c.tags.join(' ')).toLowerCase().includes(f));$('#categoryGrid').innerHTML=list.map((c,i)=>`<article class="service-card reveal" data-id="${c.id}" style="--i:${i}"><div class="service-icon ${c.color}">${c.icon}</div><div class="service-body"><span class="service-tag">${c.tags[0]}</span><h3>${c.title}</h3><p>${c.short}</p><button class="text-btn">Lihat detail <span>→</span></button></div></article>`).join('')||'<div class="empty">Layanan tidak ditemukan. Coba kata kunci lain.</div>';$$('.service-card').forEach(e=>e.onclick=()=>openDetail(e.dataset.id))}
function openDetail(id){const c=C.find(x=>x.id===id),d=D[id];if(!c||!d)return;$('#detailContent').innerHTML=`<div class="detail-hero"><button class="back-btn" onclick="closeDetail()">← Kembali</button><div class="detail-icon ${c.color}">${c.icon}</div><div><span class="eyebrow">${d.label}</span><h2>${d.title}</h2><p>${d.intro}</p></div><button class="btn primary" onclick="askAbout('${id}')">💬 Tanya SAPA FIND</button></div><div class="detail-grid"><div class="detail-main">${d.sections.map((s,i)=>`<article class="info-block"><span>0${i+1}</span><div><h3>${s[0]}</h3><p>${s[1]}</p></div></article>`).join('')}<div class="detail-note">⚠️ <div><b>Catatan</b><p>Konten ini adalah template prototype. Sebelum dipakai sebagai informasi publik, sesuaikan dengan SOP dan ketentuan resmi terbaru.</p></div></div></div><aside class="detail-side"><h3>Checklist</h3>${d.check.map(x=>`<label><input type="checkbox"> <span>${x}</span></label>`).join('')}<button class="btn ghost full" onclick="openChat()">Tanya topik lain</button></aside></div>`;$('#detail').classList.remove('hidden');location.hash='detail';window.scrollTo({top:$('#detail').offsetTop-80,behavior:'smooth'})}
function closeDetail(){$('#detail').classList.add('hidden');location.hash='layanan'}
window.closeDetail=closeDetail;
function askAbout(id){openChat();const c=C.find(x=>x.id===id);setTimeout(()=>sendMessage(c.title),150)} window.askAbout=askAbout;
function answer(q){const t=q.toLowerCase();if(/^(hai|halo|hello|hi|assalam)/.test(t))return'👋 Halo! Saya SAPA FIND. Saya bisa membantu tentang paspor baru, penggantian, hilang, rusak, anak, biaya, persyaratan, prosedur, foto, perjalanan, dan kontak.';let best=null,score=0;K.forEach(k=>{let s=k.keywords.reduce((n,w)=>n+(t.includes(w)?Math.max(2,w.length):0),0);if(s>score){score=s;best=k}});if(best)return best.text+'\n\n💡 Untuk penggunaan resmi, verifikasi kembali dengan ketentuan terbaru.';if(t.includes('kontak')||t.includes('telepon')||t.includes('email'))return`📞 ${APP_CONFIG.office.phone}\n✉️ ${APP_CONFIG.office.email}`;if(t.includes('alamat')||t.includes('lokasi'))return`📍 ${APP_CONFIG.office.address}\n🕐 ${APP_CONFIG.office.hours}`;return'🤔 Saya belum menemukan jawaban yang cocok. Coba gunakan kata kunci seperti “paspor baru”, “syarat”, “hilang”, “rusak”, “anak”, “biaya”, “foto”, “prosedur”, “lokasi”, atau “kontak”.'}
function addMsg(text,who){const d=document.createElement('div');d.className='chat-msg '+who;d.innerHTML=esc(text).replace(/\n/g,'<br>');$('#messages').append(d);$('#messages').scrollTop=99999}
function openChat(){const m=$('#chatModal');m.classList.add('open');if(!$('#messages').children.length){addMsg('👋 Halo! Saya SAPA FIND.\nSaya siap membantu Anda mencari informasi paspor. Pilih topik di bawah atau tulis pertanyaan Anda.','bot');renderSuggestions()}setTimeout(()=>$('#chatInput').focus(),100)}
function closeChat(){$('#chatModal').classList.remove('open')}
function renderSuggestions(){const qs=['Paspor baru','Syarat paspor','Paspor hilang','Paspor anak','Biaya paspor','Lokasi kantor'];$('#chatSuggestions').innerHTML=qs.map(q=>`<button>${q}</button>`).join('');$$('#chatSuggestions button').forEach(b=>b.onclick=()=>sendMessage(b.textContent))}
function sendMessage(v){if(!v)return;addMsg(v,'user');$('#chatInput').value='';setTimeout(()=>addMsg(answer(v),'bot'),350)}
function renderFAQ(){$('#faqGrid').innerHTML=APP_CONTENT.faq.map((f,i)=>`<article class="faq-card"><button><span>${String(i+1).padStart(2,'0')}</span><b>${f.q}</b><i>＋</i></button><div><p>${f.a}</p></div></article>`).join('');$$('.faq-card button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'))}
function renderChecklist(){const key='sapa-find-check';let saved=JSON.parse(localStorage.getItem(key)||'[]');$('#checklist').innerHTML=APP_CONTENT.checklist.map((x,i)=>`<label class="check-row"><input type="checkbox" data-i="${i}" ${saved.includes(i)?'checked':''}><span>${x}</span><i>✓</i></label>`).join('');$$('#checklist input').forEach(e=>e.onchange=()=>{saved=$$('#checklist input:checked').map(x=>+x.dataset.i);localStorage.setItem(key,JSON.stringify(saved));updateProgress()});updateProgress()}
function updateProgress(){const n=$$('#checklist input:checked').length,total=APP_CONTENT.checklist.length;$('#checkCount').textContent=`${n}/${total}`;$('#progressBar').style.width=(n/total*100)+'%'}
function renderOffice(){const o=APP_CONFIG.office;$('#officeInfo').innerHTML=[['📍','Alamat',o.address],['🕐','Jam layanan',o.hours],['📞','Telepon',o.phone],['✉️','Email',o.email],['🌐','Website',o.websiteLabel]].map(x=>`<div><span>${x[0]}</span><div><small>${x[1]}</small><b>${x[2]}</b></div></div>`).join('')}
function searchAll(q){const t=q.toLowerCase().trim();if(!t){$('#searchResults').innerHTML='';return}const r=K.filter(k=>(k.title+' '+k.text+' '+k.keywords.join(' ')).toLowerCase().includes(t)).slice(0,8);$('#searchResults').innerHTML=r.map(k=>`<article><span>⌕</span><div><b>${esc(k.title)}</b><p>${esc(k.text)}</p></div></article>`).join('')||'<div class="empty">Tidak ada hasil. Coba kata kunci “paspor”, “syarat”, “hilang”, atau “biaya”.</div>'}
function setupNav(){$$('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));$$('[data-nav]').forEach(a=>a.onclick=e=>{const id=a.getAttribute('href');if(id==='#detail'){e.preventDefault();return}setTimeout(()=>document.querySelector(id)?.scrollIntoView({behavior:'smooth'}),0)});}
renderCategories();renderFAQ();renderChecklist();renderOffice();setupNav();
$('#serviceSearch').oninput=e=>renderCategories(e.target.value);$('#searchBtn').onclick=()=>searchAll($('#globalSearch').value);$('#globalSearch').oninput=e=>searchAll(e.target.value);
$('#startBtn').onclick=openChat;$('#heroChatBtn').onclick=openChat;$('#fab').onclick=openChat;$('#bottomChat').onclick=openChat;$('#helpBtn').onclick=()=>toast('Pilih Layanan, gunakan Smart Search, atau buka Chat SAPA FIND.');$('#resetCheck').onclick=()=>{localStorage.removeItem('sapa-find-check');renderChecklist();toast('Checklist direset.')};
$('#chatForm').onsubmit=e=>{e.preventDefault();sendMessage($('#chatInput').value.trim())};$$('[data-close]').forEach(b=>b.onclick=()=>{b.closest('.modal').classList.remove('open')});$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal.open').forEach(m=>m.classList.remove('open'));closeDetail()}});
setTimeout(()=>$('#splash').classList.add('hide'),850);
