const APP_CONTENT={
 categories:[
  {id:'baru',icon:'🛂',title:'Paspor Baru',short:'Panduan permohonan paspor pertama kali.',color:'blue',tags:['baru','pertama kali']},
  {id:'ganti',icon:'🔄',title:'Penggantian Paspor',short:'Untuk paspor habis berlaku, halaman penuh, perubahan data, dan lainnya.',color:'green',tags:['ganti','habis berlaku']},
  {id:'hilang',icon:'⚠️',title:'Paspor Hilang',short:'Langkah awal, dokumen, dan hal yang perlu diperhatikan.',color:'red',tags:['hilang','lapor']},
  {id:'rusak',icon:'🪪',title:'Paspor Rusak',short:'Informasi penanganan paspor rusak atau tidak layak.',color:'orange',tags:['rusak','sobek']},
  {id:'anak',icon:'👨‍👩‍👧',title:'Paspor Anak',short:'Persiapan dokumen untuk pemohon anak.',color:'purple',tags:['anak','bayi']},
  {id:'biaya',icon:'💳',title:'Biaya & Pembayaran',short:'Panduan mengecek tarif dan menyiapkan pembayaran.',color:'cyan',tags:['biaya','tarif']},
  {id:'syarat',icon:'📋',title:'Persyaratan Dokumen',short:'Checklist dokumen berdasarkan jenis layanan.',color:'indigo',tags:['syarat','dokumen']},
  {id:'prosedur',icon:'🕐',title:'Prosedur & Alur',short:'Gambaran alur dari persiapan sampai selesai.',color:'blue',tags:['prosedur','alur']},
  {id:'foto',icon:'📸',title:'Foto, Biometrik & Wawancara',short:'Persiapan sebelum proses foto dan biometrik.',color:'gold',tags:['foto','biometrik']},
  {id:'cek',icon:'✅',title:'Cek Sebelum Datang',short:'Checklist sederhana agar tidak lupa persiapan.',color:'green',tags:['cek','persiapan']},
  {id:'perjalanan',icon:'✈️',title:'Persiapan Perjalanan',short:'Hal penting terkait masa berlaku dan perjalanan.',color:'sky',tags:['perjalanan','luar negeri']},
  {id:'kontak',icon:'📍',title:'Lokasi & Kontak',short:'Alamat, jam layanan, telepon, email, dan website.',color:'navy',tags:['lokasi','kontak']}
 ],
 details:{
  baru:{label:'LAYANAN 01',title:'Paspor Baru',intro:'Gunakan halaman ini sebagai panduan awal sebelum mengajukan paspor baru. Detail persyaratan harus disesuaikan dengan ketentuan resmi terbaru.',sections:[
   ['Siapkan dokumen','KTP/identitas yang sah, Kartu Keluarga, serta dokumen pendukung lain sesuai kondisi pemohon. Pastikan nama, tempat/tanggal lahir, dan data penting konsisten.'],
   ['Alur umum','Tentukan layanan → lakukan pendaftaran sesuai mekanisme resmi → siapkan dokumen → hadir sesuai jadwal → verifikasi → foto/biometrik/wawancara bila diperlukan → pembayaran → ikuti informasi penyelesaian.'],
   ['Sebelum datang','Cek kembali jadwal, dokumen asli, dokumen pendukung, dan ketentuan terbaru. Simpan bukti pendaftaran jika ada.'] ],check:['KTP/identitas','Kartu Keluarga','Dokumen pendukung sesuai kondisi','Bukti pendaftaran (jika ada)']},
  ganti:{label:'LAYANAN 02',title:'Penggantian Paspor',intro:'Penggantian paspor dapat dilakukan karena beberapa kondisi. Pilih alasan yang sesuai dan siapkan paspor lama bila masih tersedia.',sections:[['Alasan umum','Habis masa berlaku, halaman penuh, perubahan data, paspor rusak, atau alasan lain sesuai ketentuan.'],['Paspor lama','Bawa paspor lama jika masih ada dan dapat ditunjukkan.'],['Perubahan data','Siapkan dokumen yang membuktikan perubahan data bila penggantian berkaitan dengan perubahan identitas.']],check:['Paspor lama (jika ada)','KTP/identitas','KK','Dokumen perubahan data jika diperlukan']},
  hilang:{label:'LAYANAN 03',title:'Paspor Hilang',intro:'Paspor hilang perlu ditangani melalui prosedur khusus. Jangan membuat informasi sendiri; ikuti arahan petugas dan ketentuan resmi.',sections:[['Langkah awal','Segera laporkan kehilangan sesuai mekanisme yang ditentukan. Siapkan identitas dan dokumen pendukung yang diminta.'],['Dokumen pendukung','Keterangan kehilangan atau dokumen lain dapat diperlukan sesuai kondisi dan ketentuan.'],['Catatan penting','Jangan menggunakan paspor yang sudah dinyatakan hilang jika kemudian ditemukan tanpa mengikuti arahan resmi.']],check:['Identitas','Keterangan kehilangan jika dipersyaratkan','Dokumen pendukung','Informasi kejadian kehilangan']},
  rusak:{label:'LAYANAN 04',title:'Paspor Rusak',intro:'Paspor yang rusak dapat memerlukan penanganan berbeda tergantung kondisi kerusakannya.',sections:[['Contoh kondisi','Halaman sobek, terkena air, biodata rusak, atau kerusakan lain yang membuat dokumen sulit digunakan.'],['Saat datang','Bawa paspor yang rusak dan identitas serta dokumen pendukung sesuai arahan.'],['Perhatian','Jangan memperbaiki atau memodifikasi halaman paspor sendiri.']],check:['Paspor rusak','Identitas','Dokumen pendukung bila diminta']},
  anak:{label:'LAYANAN 05',title:'Paspor Anak',intro:'Persiapkan dokumen anak dan orang tua/wali dengan teliti sebelum mengajukan layanan.',sections:[['Dokumen anak','Siapkan identitas/dokumen anak sesuai usia dan ketentuan.'],['Dokumen orang tua/wali','Siapkan identitas orang tua/wali serta bukti hubungan keluarga bila diperlukan.'],['Pendampingan','Ikuti ketentuan kehadiran dan pendampingan pemohon anak yang berlaku.']],check:['Dokumen anak','KTP orang tua/wali','KK','Dokumen hubungan keluarga']},
  biaya:{label:'LAYANAN 06',title:'Biaya & Pembayaran',intro:'Tarif dapat berubah berdasarkan jenis paspor dan layanan. Gunakan bagian ini sebagai pengingat untuk mengecek tarif resmi terbaru.',sections:[['Sebelum membayar','Pastikan jenis paspor dan layanan yang dipilih sudah benar.'],['Bukti pembayaran','Simpan bukti pembayaran sesuai mekanisme yang diberikan.'],['Verifikasi','Untuk angka tarif terkini, arahkan pengguna ke sumber resmi sebelum dipakai dalam informasi publik.']],check:['Jenis layanan sudah benar','Cek tarif resmi terbaru','Simpan bukti pembayaran']},
  syarat:{label:'LAYANAN 07',title:'Persyaratan Dokumen',intro:'Checklist di bawah adalah template demo. Isi dapat Anda sesuaikan dengan SOP dan ketentuan resmi kantor.',sections:[['Dokumen identitas','Identitas pemohon dan dokumen keluarga/pendukung yang relevan.'],['Kondisi khusus','Tambahkan dokumen khusus jika penggantian karena hilang, rusak, perubahan data, atau kondisi lainnya.'],['Dokumen asli','Utamakan membawa dokumen asli dan salinan jika dipersyaratkan.']],check:['Identitas','KK','Dokumen pendukung','Dokumen asli','Salinan bila diperlukan']},
  prosedur:{label:'LAYANAN 08',title:'Prosedur & Alur',intro:'Gunakan alur visual ini untuk menjelaskan proses kepada pengguna secara sederhana.',sections:[['1. Persiapan','Tentukan layanan dan siapkan dokumen.'],['2. Pendaftaran','Ikuti mekanisme pendaftaran resmi yang berlaku.'],['3. Kedatangan','Datang sesuai jadwal dan bawa dokumen yang diminta.'],['4. Verifikasi','Petugas memeriksa data dan dokumen.'],['5. Biometrik','Foto, sidik jari, dan wawancara bila diperlukan.'],['6. Penyelesaian','Lakukan pembayaran dan ikuti informasi pengambilan/penyelesaian.']],check:['Pilih layanan','Dokumen siap','Jadwal dicatat','Bukti pendaftaran','Bukti pembayaran']},
  foto:{label:'LAYANAN 09',title:'Foto, Biometrik & Wawancara',intro:'Persiapan sederhana membantu proses pelayanan berjalan lebih lancar.',sections:[['Foto','Berpakaian rapi dan ikuti arahan petugas.'],['Biometrik','Ikuti proses pengambilan biometrik sesuai prosedur.'],['Wawancara','Jawab pertanyaan sesuai keadaan sebenarnya dan dokumen yang dimiliki.']],check:['Pakaian rapi','Dokumen siap','Datang sesuai jadwal']},
  cek:{label:'LAYANAN 10',title:'Cek Sebelum Datang',intro:'Gunakan checklist ini sebagai pengingat, bukan sebagai pengganti daftar persyaratan resmi.',sections:[['Checklist inti','Layanan, dokumen, jadwal, biaya, bukti pendaftaran, dan dokumen asli sudah diperiksa.'],['Jika ragu','Gunakan SAPA FIND untuk mencari topik atau tanyakan kepada petugas.']],check:['Jenis layanan','Dokumen','Jadwal','Biaya','Bukti pendaftaran','Dokumen asli','Kontak kantor','Pertanyaan sudah jelas']},
  perjalanan:{label:'LAYANAN 11',title:'Persiapan Perjalanan',intro:'Informasi perjalanan dapat berubah dan berbeda berdasarkan negara tujuan.',sections:[['Masa berlaku','Periksa masa berlaku paspor jauh sebelum keberangkatan.'],['Negara tujuan','Periksa persyaratan masuk, visa, transit, dan aturan terbaru dari sumber resmi negara tujuan.'],['Dokumen perjalanan','Simpan salinan dokumen penting secara aman.']],check:['Masa berlaku paspor','Aturan negara tujuan','Visa jika diperlukan','Salinan dokumen']},
  kontak:{label:'LAYANAN 12',title:'Lokasi & Kontak',intro:'Data kantor di bawah dapat diganti dari data/config.js.',sections:[['Alamat','Lihat kartu informasi kantor di bagian bawah aplikasi.'],['Jam layanan','Gunakan data yang telah disesuaikan dengan jadwal kantor.'],['Kontak','Telepon/email/website dapat ditampilkan sebagai jalur informasi tambahan.']],check:['Catat alamat','Catat jam layanan','Simpan kontak']}
 },
 knowledge:[
  ['paspor baru','Paspor Baru','Untuk paspor baru, tentukan layanan yang dibutuhkan, siapkan identitas dan dokumen pendukung, lalu ikuti mekanisme pendaftaran resmi terbaru.'],
  ['syarat paspor','Persyaratan Paspor','Persyaratan mengikuti jenis layanan dan kondisi pemohon. Siapkan dokumen asli dan salinan jika dipersyaratkan.'],
  ['ktp','KTP','KTP/identitas yang sah biasanya menjadi bagian penting dari identifikasi pemohon. Pastikan data konsisten dengan dokumen lain.'],
  ['kartu keluarga','Kartu Keluarga','KK dapat menjadi dokumen pendukung untuk membuktikan data keluarga. Bawa sesuai ketentuan layanan yang dipilih.'],
  ['penggantian','Penggantian Paspor','Penggantian dapat terkait habis berlaku, halaman penuh, perubahan data, rusak, atau kondisi lain. Pilih alasan yang benar.'],
  ['habis berlaku','Paspor Habis Berlaku','Untuk paspor yang habis berlaku, cek mekanisme penggantian dan persyaratan terbaru sebelum datang.'],
  ['halaman penuh','Halaman Paspor Penuh','Jika halaman paspor penuh, gunakan layanan penggantian sesuai ketentuan. Bawa paspor lama bila masih ada.'],
  ['perubahan data','Perubahan Data','Jika data berubah, siapkan dokumen resmi yang membuktikan perubahan tersebut dan ikuti prosedur penggantian.'],
  ['paspor hilang','Paspor Hilang','Segera laporkan kehilangan sesuai prosedur. Siapkan identitas dan dokumen keterangan kehilangan bila dipersyaratkan.'],
  ['lapor hilang','Lapor Kehilangan','Kehilangan paspor memerlukan penanganan khusus. Ikuti arahan petugas dan jangan mengandalkan informasi tidak resmi.'],
  ['paspor rusak','Paspor Rusak','Bawa paspor yang rusak saat pelayanan bila diminta. Jangan memodifikasi atau memperbaiki halaman sendiri.'],
  ['paspor anak','Paspor Anak','Siapkan dokumen anak, orang tua/wali, serta bukti hubungan keluarga sesuai ketentuan.'],
  ['bayi','Paspor Bayi','Untuk bayi, periksa dokumen identitas/kelahiran dan ketentuan pendampingan yang berlaku.'],
  ['biaya','Biaya Paspor','Tarif harus mengikuti ketentuan resmi terbaru. Cek jenis paspor dan layanan sebelum pembayaran.'],
  ['tarif','Tarif','Jangan menetapkan angka tarif dari prototype. Perbarui informasi sesuai sumber resmi terbaru.'],
  ['foto','Foto Paspor','Berpakaian rapi dan ikuti arahan petugas saat pengambilan foto.'],
  ['biometrik','Biometrik','Proses biometrik dilakukan sesuai prosedur pelayanan. Ikuti instruksi petugas.'],
  ['wawancara','Wawancara','Jawab pertanyaan secara benar dan konsisten dengan dokumen yang dimiliki.'],
  ['prosedur','Prosedur','Alur umum: pilih layanan → daftar → siapkan dokumen → hadir → verifikasi → foto/biometrik/wawancara bila perlu → pembayaran → penyelesaian.'],
  ['berapa lama','Waktu','Waktu penyelesaian bergantung jenis layanan dan kondisi proses. Gunakan informasi resmi terbaru untuk estimasi operasional.'],
  ['lokasi','Lokasi','Alamat dan jam layanan dapat dilihat pada kartu Informasi Kantor dan diedit melalui data/config.js.'],
  ['alamat','Alamat Kantor','Alamat demo: Jl. Dorak, Selatpanjang, Kab. Kepulauan Meranti, Riau. Sesuaikan sebelum publikasi.'],
  ['telepon','Telepon','Nomor telepon demo tersimpan di data/config.js agar mudah diganti.'],
  ['email','Email','Email kantor demo tersimpan di data/config.js dan dapat diganti tanpa mengubah halaman utama.'],
  ['sebelum datang','Sebelum Datang','Cek jenis layanan, dokumen, jadwal, biaya, dan bukti pendaftaran. Simpan dokumen penting dengan aman.'],
  ['perjalanan','Perjalanan','Periksa masa berlaku paspor dan persyaratan negara tujuan dari sumber resmi karena aturan dapat berubah.'],
  ['visa','Visa','Ketentuan visa berbeda menurut negara tujuan. Periksa sumber resmi negara tujuan atau kanal pemerintah terkait.'],
  ['salah data','Data salah','Jika menemukan ketidaksesuaian data, jangan menebak atau mengubah sendiri. Konsultasikan sesuai prosedur resmi.'],
  ['dokumen asli','Dokumen asli','Bawa dokumen asli dan salinan jika dipersyaratkan. Pastikan dokumen terbaca dan tidak rusak.']
 ].map(x=>({keywords:x[0].split('|'),title:x[1],text:x[2]})),
 faq:[
  ['Apa itu SAPA FIND?','Prototype asisten informasi berbasis web yang menyusun informasi paspor dalam kategori, detail layanan, pencarian, checklist, dan chat.'],
  ['Apakah SAPA FIND menggantikan petugas?','Tidak. SAPA FIND hanya alat bantu informasi. Keputusan dan pelayanan tetap mengikuti petugas serta ketentuan resmi.'],
  ['Apakah bisa dipakai di HP?','Bisa. Tampilan dirancang responsif dan memiliki navigasi bawah seperti aplikasi mobile.'],
  ['Apakah perlu database?','Tidak untuk prototype ini. Data tersimpan dalam file JavaScript sehingga cocok untuk GitHub Pages.'],
  ['Bagaimana menambah jawaban chatbot?','Edit data/content.js pada bagian knowledge. Tambahkan kata kunci dan jawaban baru.'],
  ['Bagaimana mengganti alamat kantor?','Edit data/config.js pada bagian office. Tidak perlu mengubah index.html.'],
  ['Bisa ditambah logo kantor?','Bisa. Ganti assets/logo.svg atau sesuaikan elemen brand.'],
  ['Bisa ditambah layanan lain?','Bisa. Tambahkan kategori dan detail baru di data/content.js.']
 ].map(x=>({q:x[0],a:x[1]})),
 checklist:['Jenis layanan sudah ditentukan','Dokumen identitas sudah disiapkan','KK/dokumen pendukung sudah dicek','Dokumen asli sudah disiapkan','Jadwal pendaftaran sudah dicatat','Biaya/tarif resmi sudah dicek','Bukti pendaftaran disimpan jika ada','Pertanyaan yang ingin ditanyakan sudah dicatat']
};
